### ISSUE TITLE
Can I run TeaCache on multiple GPUs?

### ISSUE THREAD

**Issue by Xzh-lab** [ali-vilab/TeaCache#48]
Is it possible to utilize multiple GPUs to run the code of Wan 2.1?

**Comment by yigithanyigit** [comment]
Actually I am also wondering. I am getting an error when I try it.

I am getting either cuDNN_Internal_error or `teacache_forward` context, seq_len missing error.

**Comment by yigithanyigit** [comment]
Ok, I have fixed the `TypeError` that I mentioned. I am working to fix cuDNN error.

**Comment by Xzh-lab** [comment]
Can you share the correct code, I am also getting the same error :)

**Comment by LiewFeng** [comment]
I'm occupied by other things recently. If anyone implement it, welcome to launch a PR to support it.

**Comment by yigithanyigit** [comment]
@LiewFeng Should I expect speed increase with USP compared to single-gpu?

**Comment by LiewFeng** [comment]
You can refer to [Teacache-xDiT](https://github.com/MingXiangL/Teacache-xDiT).

**Comment by quxinqq** [comment]
> Ok, I have fixed the `TypeError` that I mentioned.
> 
> cuDNN error is related with
> 
> `x = [self.patch_embedding(u.unsqueeze(0)) for u in x]` specifically ` F.conv3d(` operation inside `teacache_forward`. It outputs `CUDA error: an illegal memory access was encountered `.

Can you share how to fix `TypeError`, I also encountered same issue, thanks.

**Comment by Xzh-lab** [comment]
> > > Ok, I have fixed the `TypeError` that I mentioned.
> > > cuDNN error is related with
> > > `x = [self.patch_embedding(u.unsqueeze(0)) for u in x]` specifically ` F.conv3d(` operation inside `teacache_forward`. It outputs `CUDA error: an illegal memory access was encountered `.
> > 
> > 
> > Can you share how to fix `TypeError`, I also encountered same issue, thanks.
> 
> As far as I remember, you need to patch with `types`. should something like this;
> 
> `types.MethodType(teacache_forward, model.model)`

Could you share your modified code?

**Comment by BiologicalExplosion** [comment]
> TypeError: teacache_forward() missing 2 required positional arguments: 'context' and 'seq_len'

Could you shard your modified code?

**Comment by bookkkker** [comment]
> > TypeError: teacache_forward() missing 2 required positional arguments: 'context' and 'seq_len'
> 
> Could you shard your modified code?

Have you solved it? I meet the same problem.
